### ISSUE TITLE
Python Resources

### ISSUE THREAD

**Issue by hayleyng8** [Tuhura-Tech/wiki#149]
Functions and how to use dictionaries
Using Python Class

**Comment by Darkflame72** [comment]
As an overall concept these things would want to be covered:

- [ ] Python Basics
  - Print
  - Comments
- [ ] Variables
  - input
  - creating, updating and assigning
- [ ] Basic Python Data Types
  - What is a str, bool, int, float, etc (don't do list, dict or tuple)
- [ ] Loops
  - For loops using range
  - while loops based on variables
- [ ] Lists/Tuples
  - Creating/updating
  - Accessing by index
  - looping through using for (not single line list stuff)
- [ ] Dictionaries
  - Same stuff as lists
- [ ] Functions
  - Simple functions
  - Returning values
  - Parameters
- [ ] Types/Docstrings
  - extending functions with type hints
  - extending functions with google docstrings (easy docstring format)
- [ ] Classes
  - Basic classes
  - No inheritance, polymorphisms, etc
- [ ] Extending classes
  - all the fun OOP stuff

**Comment by Darkflame72** [comment]
I'll be splitting this into smaller individual issues so will close this one
