### ISSUE TITLE
Git Basics

### ISSUE THREAD

**Issue by Benjamin-Park** [Tuhura-Tech/wiki#156]
Expand existing git guides to include basic git workflow as well as good practices. Should also cover working with remote repos.

**Comment by Darkflame72** [comment]
This should also be linked from the contributing guide as it should be assumed people have no experience with github/git

**Comment by Darkflame72** [comment]
Can point to better external resources such as https://antonz.org/git-by-example/ instead.

**Comment by Darkflame72** [comment]
Improve base resources as a quick reference guide and also point to external resources and cheatsheets
