### ISSUE TITLE
Adding more to Godot docs

### ISSUE THREAD

**Issue by BoopEnthusiast** [Tuhura-Tech/Wiki#162]
**Is your feature request related to a problem? Please describe.**
The Godot docs don't teach enough about all the intricacies of making a real game.

**Describe the solution you'd like**
Another page or two describing how to make real games

**Describe alternatives you've considered**
Adding more to the 2D and 3D docs. It just doesn't feel like it fits with the idea and won't be dedicated to all the nuances, plus the pages are already long

**Comment by Darkflame72** [comment]
Could also include example games:

## 2D
- [ ] Top down shooter
- [ ] worldbuilder, city game, tower defense, etc
- [ ] racing game

## 3D

- [ ] shooter
- [ ] racing game
