### ISSUE TITLE
Add Tutorial Component

### ISSUE THREAD

**Issue by Darkflame72** [Tuhura-Tech/wiki#191]
Add tutorial components similar to those used by the [Astro docs](https://docs.astro.build/en/tutorial/0-introduction/).

**Comment by arimulligan** [comment]
PSA: Currently implementing this in the [Python turtle issue.](https://github.com/Tuhura-Tech/wiki/issues/307)

**Comment by arimulligan** [comment]
Added a [green checklist component](https://github.com/Tuhura-Tech/wiki/tree/checklist-component)

**Comment by arimulligan** [comment]
I have finished this - it is inside the python turtle issue - hope you all like it! There's an explanation on how to use it inside the `tuhura-tech/contribute.mdx` file. 
The branch isn't ready yet because I haven't finished the actual python turtle tutorial but that will be finished very soon!
