### ISSUE TITLE
Python Turtle shapes/patterns

### ISSUE THREAD

**Issue by Darkflame72** [Tuhura-Tech/wiki#307]
Basic shapes and patterns using turtle as a tutorial.

This should teach these concepts:
- variables
- for loops
- basic math around shapes (eg 5 sides is 360/5).
- lists (colour changing).

**Comment by arimulligan** [comment]
Keen to do this! Would we be implementing the [Astro docs](https://docs.astro.build/en/tutorial/0-introduction/) and editing the already made [Turtle page](https://wiki.tuhuratech.org.nz/python/turtle/) on the Wiki?
