### ISSUE TITLE
All pages of type 'tutorial' are merged into a single lesson track regardless of directory

### ISSUE THREAD

**Issue by lillianhidet** [Tuhura-Tech/wiki#364]
Regardless of directory organization all pages marked as 'type: tutorial' are merged into the same lesson track.

- Expected behavior:
 would be that tutorial lesson tracks are directory based, rather than being across all files.

- To reproduce:
add 'type: lesson' the header of any page, and it will now appear as part of the Python Turtle lesson track.

![image](https://github.com/user-attachments/assets/a5267e6e-de4b-4f4c-8bda-abc772db963f)

**Comment by arimulligan** [comment]
Pushed to [godot dungeon crawler resource](https://github.com/Tuhura-Tech/wiki/pull/360)
